server:
  port: 8090
spring:
  datasource:
    password: 666666
    username: root
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver

